[build]
  # Build command for Netlify
  command = "npm run build"
  
  # Directory to publish
  publish = "dist"

[build.environment]
  # Node.js version
  NODE_VERSION = "20"
  
  # Build environment
  NODE_ENV = "production"

# Redirect rules for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/styles/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/scripts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Netlify Functions (if using serverless functions)
[functions]
  directory = "netlify/functions"

# Form handling (if needed)
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true
